galaxy_info:
  author: Jonathan Davila 
  description: Installs AWS Code Deploy Agent 
  company: Red Hat, Inc 
  issue_tracker_url: http://example.com/issue/tracker
  license: MIT 
  min_ansible_version: 2.0 
  github_branch: master
  platforms:
  - name: Amazon
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: EL
    versions:
    - all

  galaxy_tags:
    - amazon
    - aws
    - code_deploy
    - codedeploy

dependencies: []
